### ISSUE TITLE
Confused about installation (Step 5)

### ISSUE THREAD

**Issue by 3raxton** [AlexPerathoner/SlimHUD#10]
Hey, @AlexPerathoner great work on this! I have it installed, and I'm trying to remove the regular HUDs from apple, but I'm having issues with step 5 in the README. Can you explain what step 5 does and what ```sudo mount -uw /; killall Finder``` means? 

I haven't been able to find any documentation about ```sudo mount -uw``` online and would like to make sure what I am doing is safe. Can you share any info with me? 

Great work again. I absolutely love this app!

**Comment by AlexPerathoner** [comment]
> sudo allows a permitted user to execute a command as the superuser or another user.
Mount is used to mount disks. The -u flag indicates that the status of an already mounted file system should be changed. -w means to mount the file system read-write. The file system is "/" aka root.
The killall utility kills processes selected by name. Since it's Finder, it will just restart and reflect the change you've just made.
This isn't permanent, there are more steps involved for that.

Source: [reddit](https://www.reddit.com/r/osx/comments/czkgn9/how_to_change_systemlibrarylaunchagents_in/eyzm42w?utm_source=share&utm_medium=web2x)

This is needed as in the last versions of MacOS the system files (like /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist that you'll modify in step 6) are stored in a different disk partition and being an administrator and having System Integrity Protection disabled still isn't enough to access them.

PS: note that the right command is `sudo mount -uw /`, not `sudo mount -uw`

**Comment by 3raxton** [comment]
Wow, that's absolutely wild that even with disabling SIP they still can't be accessed. I appreciate that you shared this information with me. 

I've gone through removing the text between the <plist> tags but still have the overlays. Any ideas on what I could do on top of this?

**Comment by AlexPerathoner** [comment]
If you try to open the OSDUIHelper file with Xcode do you get an error saying that the document isn't in the correct format?

**Comment by 3raxton** [comment]
Yep, that is exactly what happens.

**Comment by AlexPerathoner** [comment]
Ok that is what we are trying to accomplish with all the steps. If MacOS can't open that file it should also not be able to display the huds....
You have probably already restarted your machine, right?

**Comment by 3raxton** [comment]
I haven't but will be sure to do so in the morning. Is SIP required to be turned back on?

**Comment by AlexPerathoner** [comment]
It's not, but it's recommended as it increases protection etc etc
At the moment the agent responsible for the huds is still loaded in the cache so you first have to restart your Mac to have the changes to take effect.

**Comment by 3raxton** [comment]
I understand. I'll be sure to restart my machine and see if that clears up the issues I've been having. Thanks for your help.

**Comment by 3raxton** [comment]
Restart worked, thanks again for your help. Solid work on SlimHUD, glad I can tweak my Mac a bit further with it! 🙌
