### ISSUE TITLE
Can't verify/open on latest macOS

### ISSUE THREAD

**Issue by danispringer** [AlexPerathoner/SlimHUD#139]
### Before opening the issue, have you...?

- [x] Searched for existing issues
- [X] Updated SlimHUD to the latest version (if applicable)

### Describe the bug

Can't verify/open on latest macOS

### Steps to reproduce

brew install, double click on app in Applications folder

### Expected behavior

launch

### Environment Information (please complete the following information)

```markdown
- macOS version:13.4 (22F66)
- Mac model: M1 Air
- Monitor(s): N/A
- Apple Silicon/M1 (yes or no): yes
```

**Comment by AlexPerathoner** [comment]
Are you sure that SlimHud isn't already running? e.g. if you try changing the volume after opening it, does the default macOS hud still get shown?
I can see how this behaviour can be quite confusing, which is why I'm working on #116

**Comment by DaniSpringer** [comment]
> Are you sure that SlimHud isn't already running? e.g. if you try changing the volume after opening it, does the default macOS hud still get shown?
> I can see how this behaviour can be quite confusing, which is why I'm working on #116

Gonna retry on June 5th 😉
Thank you

**Comment by aremmell** [comment]
There is a similar concern, at least on this version of macOS (13.5 (22G74)) when installing via brew, I get this upon double-clicking the icon from Applications:

<img width="372" alt="Screenshot 2023-08-03 at 03 39 56" src="https://github.com/AlexPerathoner/SlimHUD/assets/812759/f18cca27-cddc-4a08-b2b1-14ac69476782">

In order to get 'round it, you need to hold ⌥ and right-click, choosing Open while still holding the option key down. This will let you bypass the restriction, but you should probably look into why it's happening in the first place.

Perhaps Homebrew just moving the .app file to Applications upsets the OS–or there's some interface you're supposed to implement that's missing ("software needs to be updated..."). I'm not sure. I looked through Console and didn't find anything relevant, but I did notice that the following messages appear to be spamming on repeat every half second or so:

<img width="771" alt="Screenshot 2023-08-03 at 04 03 59" src="https://github.com/AlexPerathoner/SlimHUD/assets/812759/079c922b-d029-4d45-8d0a-7a1e2d3a0539">

**Comment by AlexPerathoner** [comment]
It's probably because I'm not part of the Apple Developer Program anymore.
The console logs are weird, though - but unrelated

**Comment by malicious** [comment]
I'm running SlimHUD 1.5.1 on macOS 13.5, so it's probably signing-relrated.  
Fyi on a different system, here's what Apparency shows:

![image](https://github.com/AlexPerathoner/SlimHUD/assets/38064672/8a0a79d4-952a-4772-81ab-1c91e61d1b4e)

**Comment by Zac08** [comment]
> There is a similar concern, at least on this version of macOS (13.5 (22G74)) when installing via brew, I get this upon double-clicking the icon from Applications:
> 
> <img alt="Screenshot 2023-08-03 at 03 39 56" width="372" src="https://private-user-images.githubusercontent.com/812759/258073921-f18cca27-cddc-4a08-b2b1-14ac69476782.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODcxNTIsIm5iZiI6MTcwNjU4Njg1MiwicGF0aCI6Ii84MTI3NTkvMjU4MDczOTIxLWYxOGNjYTI3LWNkZGMtNGEwOC1iMmIxLTE0YWM2OTQ3Njc4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMzU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTU0MTY3ZTE4MzQyYjNkYWEyYjQ2NGE4MTg5ODllZDM2ODE5MDM2MWM2MjEyNmI3MzMzNTc4OWE3OGMyODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BIgY33LRbBDy8rTqJ21w4HoEbFT4xiJtJYSm-TvvJFk">
> In order to get 'round it, you need to hold ⌥ and right-click, choosing Open while still holding the option key down. This will let you bypass the restriction, but you should probably look into why it's happening in the first place.
> 
> Perhaps Homebrew just moving the .app file to Applications upsets the OS–or there's some interface you're supposed to implement that's missing ("software needs to be updated..."). I'm not sure.
> 
> I looked through Console and didn't find anything relevant, but I did notice that the following messages appear to be spamming on repeat every half second or so:
> 
> <img alt="Screenshot 2023-08-03 at 04 03 59" width="771" src="https://private-user-images.githubusercontent.com/812759/258077447-079c922b-d029-4d45-8d0a-7a1e2d3a0539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODcxNTIsIm5iZiI6MTcwNjU4Njg1MiwicGF0aCI6Ii84MTI3NTkvMjU4MDc3NDQ3LTA3OWM5MjJiLWQwMjktNGQ0NS04ZDBhLTdhMWUyZDNhMDUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQwMzU0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjQ3MzIwNTQ3NDhiOWM5MTkyMGM4YjcwN2Q1Mzg2NDUxNzViYWE4MzM5ZTcyMjQwMTliZWI4MzEzYjM5OGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N3tBifhK_q89lmpAyJJL_4w3dpKuCUGQ_OteZwC5rZA">

All you need to do In this case is go to: Settings > Accessibility > (then scroll down a bit) then you'll find something that looks a bit like this
<img width="406" alt="Screenshot 2024-01-30 at 4 57 40 PM" src="https://github.com/AlexPerathoner/SlimHUD/assets/145438617/7a96fa88-7565-4354-a6f9-e14fc4c69526">

Just click open anyway, and you should be good to go :)

**Comment by AlexPerathoner** [comment]
This is because I'm not part anymore of the Apple Developer Program (99€ per year just to sign this open source app is too much as a student!).
Because the automatic update system verifies that the signing of the new version is the same as the old one, I'll propably keep it unsigned even if I should someday get into the program.
The alarming message is just Apple trying to scare people off from non-App Store distribution. As @Zac08 pointed out, you can just ignore it by opening it anyway in the System Preferences. Even faster, right click on the app (**not** double click) > open.
