### ISSUE TITLE
Redesign Preferences Window

### ISSUE THREAD

**Issue by AlexPerathoner** [AlexPerathoner/SlimHUD#87]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Too much stuff going in the preferences window, chaotic, not nice.

### Describe the solution you'd like

Something that doesn't hurt when I look at it

**Comment by AlexPerathoner** [comment]
Any design suggestion is more than welcome!

**Comment by kaydenanderson** [comment]
hey! i made a mockup of a possible redesign for your settings pane. let me know what you think! i'd love to get some feedback - negative or positive :)
![Style](https://user-images.githubusercontent.com/104660117/212500805-996cf9a7-9798-425b-940f-d10
![About](https://user-images.githubusercontent.com/104660117/212500812-f1159b46-644a-4e34-a709-3d210fb274ba.png)
![Config](https://user-images.githubusercontent.com/104660117/212500815-da151219-43fb-4aaa-a1ce-de61f6fb2e44.png)
![Design](https://user-images.githubusercontent.com/104660117/212500816-fc2eb8e2-0d9d-416c-b0e6-8865d055680b.png)
d43789837.png)

**Comment by AlexPerathoner** [comment]
This too!? I'm touched ❤️
Looks amazing, I love it!

One thing: #92 at some point I'll probably add a way to have multiple animations, and a button to replay them.
Something like this, found in System Preferences > Sound
![image](https://user-images.githubusercontent.com/31958579/212501719-c66bc810-69dc-4da4-978c-030655d8dbaf.png)
Do you think that could be added as well?

**Comment by kaydenanderson** [comment]
i’d love to! i’ll get on it 🫡

**Comment by AlexPerathoner** [comment]
By the way, how did you create those mockups? Is there a way to export them as a `.storyboard` / `.xib`? Or do they need to be done again in Xcode?

**Comment by kaydenanderson** [comment]
okay - i've mocked up a few different ideas for the design. here's what it looks like with animations **_enabled_** as usual:
![DesignRev_Normal](https://user-images.githubusercontent.com/104660117/212526443-0b490510-33ae-4214-8c70-496ec1a70636.png)
and if the user decides to **_disable_** them, i've imagined two ways (though there are definitely infinitely more and effective ways) to go about this. one: keep the selection dropdown visible but disable it; or two: use some fancy graphics and make the checkboxes move around a bit while completely hiding the dropdown box. 
![a](https://user-images.githubusercontent.com/104660117/212526514-faf89c62-0a66-4e76-8c82-871133e74c3c.png)
if you have a different idea that you want me to mock up i'd be more than happy to! 😄
i used a swiftUI button instead of a circle play indicator just because that felt more in-line with the current design aesthetic but i can replace it if you want. let me know.
as for the software i used - Sketch. i know that a lot of designers use this so i imagine there's a way to import it into Xcode. here's the file if you want to play around with it :D
https://file.io/iw0mmPSigz7M
let me know if i can help at all with the design process. if there's something that will make writing this easier in Xcode then just delegate - i've got a little extra on my hands this long weekend (it's MLK day in the US).

**Comment by AlexPerathoner** [comment]
What if the drop menu has an option "None", which disables the test button and we remove the animation checkbox?

**Comment by kaydenanderson** [comment]
i can definitely do that!

**Comment by AlexPerathoner** [comment]
If you find a way to convert it to a storyboard it would be really cool. If there is none and you really want to, you can also do it by hand and push it to #102 . I'm getting near to the end of the semester so I'll have a bit less time for this project

**Comment by AlexPerathoner** [comment]
whops, didn't realise that you already posted it - next time write a new comment or I won't receive a notification on the edit ;)

**Comment by kaydenanderson** [comment]
sounds good! i can mock that up. do you want me to just extend the existing elements to fill the space or would you like me to add another component in place of it?
also, i took your feedback from reply 1383225894 and drafted it up (removing the Animations checkbox and replacing it with a dropdown menu instead that can disable the Test button accordingly). 
![DesignRev2_SwipeIn](https://user-images.githubusercontent.com/104660117/213276701-032034bf-66d8-447f-b9e3-4d2c80e27462.jpg)
let me know if you want me to change it/keep it/revert to a previous design iteration!
